language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t aragorn1992gb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aragorn1992gb/docker-react npm run test
